FROM openjdk:10-jdk-slim
MAINTAINER Wang Eric GaoXiang <wgx731@gmail.com>

ARG JAR_FILE
ADD target/${JAR_FILE} /opt/webapp/app.jar

# Run the image as a non-root user
RUN useradd -ms /bin/bash runner
USER runner

WORKDIR /opt/webapp

CMD java -Djava.security.egd=file:/dev/./urandom -jar app.jar
