language: java

sudo: required

jdk:
- openjdk10

services:
- docker

jobs:
  include:
  - stage: sonar check
    script:
    - "mvn sonar:sonar -Dsonar.projectKey=wgx731_dr-spring -Dsonar.organization=wgx731-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=2c841bb7b67fe6f4eaff901ced1849a173efa011 || exit 107"
  - stage: build artifact and documentation
    if: branch = master
    script:
    - "$PWD/scripts/clean-up.sh"
    - "$PWD/scripts/build-artifacts.sh || exit 101"
    - mkdir -p $PWD/dr-spring-gateway/target/docs/postman || exit 102
    - nvm install 8.11.3 || exit 103
    - nvm use 8.11.3 || exit 104
    - npm i -g restdocs-to-postman@v2.0.0  || exit 105
    - "$PWD/scripts/generate-postman.sh || exit 106"
  - stage: test coverage and make release
    if: branch = dev
    script:
    - "$PWD/scripts/test-coverage.sh || exit 300"
addons:
  sonarcloud:
    organization: wgx731-github
    token:
      secure: fds9wfk30yYlbpdf2pUWNDFigSj85R5Cs36o1jd/+k7OwH//7byz3avaVVBQ9lKriGKJCNyNmJnOmD9bBV9dF7WaS4ju173ZUCHfVcF9f2IBM2dxRn0urM5C6xVFOo64SaBSV+AsLQpxtGK36zPU515B3Okepspi4iwd9kGyQ/hOj5KwNiPT1sxuh8vQOhjeF+n7ffDAMwC9NEUtimi+gb9PCOTa5Xbl2qphDQSKrny0+4WRSiM5S8+mjae6GthhsqaENm8/1jGB2k40yhmViljucGNjxo/zBvly+CwKUjDIqR7EOqg6Kl2DKKhO3aUsDBwSHMQl/RG5C98fG5BIIaRUmjP1VMb5F7eu1ezJMba80N50N+7OEqbcDwt2ZOW1OCK8AlFgb7nB3cQtLIbbtQPHXa0VJVlu54b5L10iOwHhb/ct/Cq9xsmVG61b426K1r9aMm9MCkppOpEJsfd5jBnwozZXw5EZiADq/VK9BdF8Us948XRdirdjxOZ0uYF3iSRT7UPJXVBNK6YlREa4BMiPnN9UUvysGy4Ww9JmIvIPIQPLe/RCSTB3acP7a3Ft+9iBkhyMXA9zPC4YZN1Njiqb1F3K2Wx51GMbO0o5XMVnxblfgPnKMwJsB+rA/x4Xy9Qh4LLL/ojMxeFDNnNe4Hd2YxdcTltydg60+0go5bo=
env:
  global:
    secure: ndh+U5rQrkLFh25c6DMKBvPWnd8PxGCPZ8HBQACvh5vA6XndXCQn5DDMhdoi/+UCDWSeVPUNNQOw4miwPeRZJ/jmooj5mK63u2bRzD3O+LY6r/jZBhGtylbQZAUEYHjF/UbGaW9KmNluLqaA+nC772qCwCa65UQKVc/lV8coy0xm719m6E/A4NfR7bk4x9y0MDBO4wRPFFtfmvhPTEJ7NnNp/tUS8uJJv0hEDnk25YAT4ceF/Bl1RaULloyHgsHKaW+6qj3yKf8Tj6Q6V0+XfMK49tayNA1kyIENqjz8fY+XKh09ODv5Bn9tbFMZO+N9Jwu5K1MOeeN4lvYbva8lF5Q2Osy13j1wLRN+9Fd240G2HsiPdSAhUyFZpd5YXApLlAEzepOkjUlv400MLvFrZM8vhhIllBi8KOgSp7uFZHAweOk9fwjwgClp59t4ORMaQPAgZ95YKcl7DXYTTrhr0LT9LpqLZHqyuXCX2xDZXs92ffvs7homguxsVZp/uRo9QresSQB5wxm/ajj4xIUga7GqIcrYy883QG66sEIX606V3jICjeWiazmO21cDKTTTQBhsUnMvYgnJuRLyPuT7w6aYrT8b3RobNnGf1zJakouTgHU13v9Qgx5p82XOCNJzfkTDv4r0sGOm6+VGsr6BYzkBY/0/TV6qhD0OF9vq5Ds=
