language: java

sudo: required

jdk:
- openjdk10

services:
- docker

jobs:
  include:
  - stage: build artifact and documentation
    if : branch = master
    script:j
    - "$PWD/scripts/clean-up.sh"
    - "$PWD/scripts/build-artifacts.sh"
    - "docker run --rm -v $PWD:/playground wgx731/gitlab-haile $PWD/scripts/generate-postman.sh"
    - "docker run --rm -v $PWD:/playground -e 'APIMATIC_KEY=$APIMATIC_KEY' wgx731/gitlab-haile $PWD/scripts/generate-openapi.sh"
    - "$PWD/scripts/make-release.sh"
    - "$PWD/scripts/build-images.sh"
    after_success:
    - "docker login --username=_ --password=$HEROKU_TOKEN registry.heroku.com"
    - "docker push registry.heroku.com/dr-spring"

  - stage: test coverage and make release
    if : branch = dev
    script:
    - "$PWD/scripts/test-coverage.sh"
