language: java

sudo: required

jdk:
- openjdk10

services:
- docker

jobs:
  include:
  - stage: build artifact and documentation
    if : branch = master
    script:
    - "$PWD/scripts/clean-up.sh"
    - "$PWD/scripts/build-artifacts.sh || exit 101"
    - "mkdir -p $PWD/api-gateway/target/docs/postman || exit 102"
    - "nvm install 8.11.3 || exit 103"
    - "nvm use 8.11.3 || exit 104"
    - "npm i -g restdocs-to-postman@v2.0.0  || exit 105"
    - "docker run --rm -v $PWD:/playground wgx731/gitlab-haile ./scripts/generate-postman.sh || exit 106"
    - "mkdir -p $PWD/api-gateway/target/docs/openapi || exit 107"
    - "docker run --rm -v $PWD:/playground -e 'APIMATIC_KEY=$APIMATIC_KEY' wgx731/gitlab-haile ./scripts/generate-openapi.sh || exit 108"
    - "$PWD/scripts/build-images.sh || exit 109"
    after_success:
    - "$PWD/scripts/make-release.sh || exit 200"
    - "docker login --username=_ --password=$HEROKU_TOKEN registry.heroku.com || exit 201"
    - "docker push registry.heroku.com/dr-spring || exit 202"

  - stage: test coverage and make release
    if : branch = dev
    script:
    - "$PWD/scripts/test-coverage.sh || 300"
