language: java

jdk: oraclejdk9

sudo: required

branches:
  only:
  - master
  - dev

services:
  - docker

script: "./mvnw clean package -Dmaven.javadoc.skip=true -B -V"

after_success:
  - "cat $TRAVIS_BUILD_DIR/common/target/site/jacoco/jacoco.csv"
  - "cat $TRAVIS_BUILD_DIR/web/target/site/jacoco/jacoco.csv"
